HOST: http://www.example.com

--- Example ---


--
Fotografie
--


Nahravani fotografii pro uzivatele
GET /photos/1
< 200
< Content-Type: application/json
{
    "id": 12, 
    "src": "/content/12.jpg"  
} 
  