HOST: http://www.example.com

--- Example ---


--
Fotografie
--


Nahravani fotografii pro uzivatele
GET /photos/{id}
< 200
< Content-Type: application/json
{
    "id": 1, 
    "src": "/content/1.jpg"
}



